[FEAT] server host 수정

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -196,10 +196,10 @@ jobs:
       - name: Health Check
         run: |
           # Wait for deployment to stabilize
-          sleep 30
+          sleep 20
           
           # Attempt to call health endpoint (replace with your actual health endpoint)
-          HEALTH_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.EC2_HOST }}:8081/actuator/health || echo "failed")
+          HEALTH_STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://${{ secrets.EC2_HOST }}:8081/actuator/health || echo "failed")
           
           if [ "$HEALTH_STATUS" == "200" ]; then
             echo "Application is healthy!"
